
## Springboot config!

########################################################
# SWAGGER DOCS API                                     #
########################################################

#springdoc swagger
springdoc:
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true
    enabled: true
  api-docs:
    path: /api-docs
    version: openapi_3_1
    enabled: true
  packagesToScan: com.javatpoint.presentation.entrypoint

spring:
  application:
    name: spring-mvc-api
    description: spring-mvc-api
    version: 1.0.0
  jpa:
    show-sql: true # Naming strategy
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy   # The SQL dialect makes Hibernate generate better SQL for the chosen database
    generate-ddl: true
    database: DERBY
    properties:
      hibernate:
        globally_quoted_identifiers: true
    main:
      allow-bean-definition-overriding: true
		
database:
  derby:
    datasource:
      jndi-name: jdbc/eventjpadatasource

# Log settings (INFO, ERROR, DEBUG)
logging:
  level:
    root: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

handlers: java.util.logging.ConsoleHandler.level=INFO
org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.level: WARNING

########################################################
# Show details of health endpoint                      #
########################################################
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
    base-path: /
    path-mapping:
      health: healthcheck
      prometheus: metrics
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411
      sampling:
        probability: 1.0